controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

pdf_generate:
    path: /pdf/generate
    controller: App\Controller\PdfController::generatePdf

pdf_generate_groupe:
    path: /pdf/generateGroupe
    controller: App\Controller\PdfController::generateGroupePdf
